[package]
name = "docsearch"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
resolver = "2"

[dependencies]
log = "0.4.14"
reqwest = { version = "0.11.4", default-features = false, features = ["gzip", "rustls-tls"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
serde_repr = "0.1.7"
thiserror = "1.0.26"

[dev-dependencies]
env_logger = "0.9.0"
tokio = { version = "1.9.0", features = ["macros", "rt"] }
