[package]
name = "docsearch"
version = "0.2.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
rust-version = "1.56"
license = "MIT"
readme = "README.md"
description = "Resolve crate items to rustdoc URLs."
homepage = "https://github.com/dnaka91/docsearch"
repository = "https://github.com/dnaka91/docsearch"
categories = ["parser-implementations"]
keywords = ["mapping", "rustdoc", "search-index"]
include = ["src/**/*", "LICENSE", "README.md", "!**/fixtures/**/*", "!**/snapshots/**/*"]

[dependencies]
log = "0.4.14"
reqwest = { version = "0.11.6", default-features = false, features = ["gzip", "rustls-tls"] }
semver = { version = "1.0.4", features = ["serde"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
serde_repr = "0.1.7"
thiserror = "1.0.30"
unicode-xid = "0.2.2"

[dev-dependencies]
env_logger = "0.9.0"
insta = { version = "1.8.0", features = ["glob"] }
tokio = { version = "1.12.0", features = ["macros", "rt"] }
