[licenses]
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["CC0-1.0"], name = "tiny-keccak" },
    { allow = ["MIT", "ISC", "OpenSSL"], name = "ring" },
    { allow = ["MPL-2.0"], name = "webpki-roots" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]
